return {
	{
		Name = "Nouveau-né",
		PowerMult = 1,
		RateMult = 1,
		MaxLevel = 10,
		Cost = 0,
	},
	{
		Name = "Jeune",
		PowerMult = 2,
		RateMult = 1.5,
		MaxLevel = 25,
		RequireLevel = 10,
		Cost = 500,
	},
	{
		Name = "Adulte",
		PowerMult = 4,
		RateMult = 2.5,
		MaxLevel = 50,
		RequireLevel = 25,
		Cost = 5000,
	},
	{
		Name = "Prime",
		PowerMult = 8,
		RateMult = 5,
		MaxLevel = 100,
		RequireLevel = 50,
		Cost = 50000,
		RequiresRelic = true,
	},
}
